### Creation of Array

In [1]:
import numpy as np


In [3]:
a1=np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [4]:
a2 = np.array([1.1,2.2,3.3,4.4])
a2

array([1.1, 2.2, 3.3, 4.4])

In [5]:
type(a2)
a2

array([1.1, 2.2, 3.3, 4.4])

In [9]:
a4 = np.array([[[1,2],[3,4]],[[5,7],[6,9]]])
a4

array([[[1, 2],
        [3, 4]],

       [[5, 7],
        [6, 9]]])

In [10]:
c=np.array([[1,2],[3,4]],complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [11]:
c=np.array([[1,2],[3,4]],float)
c

array([[1., 2.],
       [3., 4.]])

In [12]:
d = np.empty((3,4))
d

array([[1.32965532e-311, 2.86558075e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 2.42336543e-057, 5.45390280e-090,
        2.67734072e+184],
       [1.00512147e-047, 4.32565349e-037, 6.48224659e+170,
        5.82471487e+257]])

In [13]:
d = np.zeros((3,4))
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
d = np.ones((2,2))
d

array([[1., 1.],
       [1., 1.]])

In [27]:
d = np.full((3,3),2.77)
d

array([[2.77, 2.77, 2.77],
       [2.77, 2.77, 2.77],
       [2.77, 2.77, 2.77]])

In [17]:
d = np.random.random((4))
d

array([0.00937933, 0.2174414 , 0.66298497, 0.58500315])

In [18]:
s1 = np.arange(10)
s1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
d = np.arange(5)
d

array([0, 1, 2, 3, 4])

In [26]:
d1 = np.arange(0,20,5)
d1

array([ 0,  5, 10, 15])

In [21]:
d = np.linspace(0,2,5)
d

array([0. , 0.5, 1. , 1.5, 2. ])

In [29]:
f1 = np.eye(3)
f1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
f2 = np.identity(3)
f2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])