# Numpy Session
# Numerical Python
We are going to learn about
* np.array
* np.shape
* np.arange
* np.linspace
* np.reshape

import numpy as np

#creating array
arr1 = np.array([1,2,3])
print(arr1)

#Type of Array
print(type(arr1))

#check dimension of array
print(arr1.ndim)

#print shape of array
print(arr1.shape)

#-------------------------
#create 2-D array
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]

arr2 = np.array((list1,list2,list3))
print(arr2)
print(arr2.shape)           #tell you (row,col)in the array
print(type(arr2))

#-------------------------
#create new array using np.arange(start, end, stepsize) for 1-D
a1=np.arange(0 ,16)
print(a1)

a2 = np.arange(20)
print(a2)

a3 = np.arange(0,11,0.2)
print(a3)


#-------------------------
#create 2-D array using np.arange(start, end, stepsize)and reshape(n,n)
a1=np.arange(0 ,16).reshape(4,4)
print(a1)

r1 =np.arange(0,12).reshape(3,4)     # 3X4 matrix
print(r1)

r2 = np.arange(0,12).reshape(4,3)     # 4X3 matrix
print(r2)


#-------------------------
#np.linspace(start, end, element to be evenly distribute)
b1 = np.linspace(0.2,0.8,4)         #b/w 0.2-0.8 i want 4 element
print(b1)

b2 = np.linspace(1,100,25).reshape(5,5) #b/w 1 - 100 i want 25 elements
print(b2)

b3 = np.linspace(51,99,25).reshape(5,5) #b/w 51 - 99 i want 25 elements
print(b3)





#  INDEXING


In [4]:
import numpy as np


In [9]:
arr1 = np.arange(0,16)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
arr1[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [11]:
arr1[6:9]


array([6, 7, 8])

In [13]:
a1 = arr1.reshape(4,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
a1[1:3,0:3]

array([[ 4,  5,  6],
       [ 8,  9, 10]])

In [15]:
a1[0:4,0:1]

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [16]:
a1[2:3,0:3]

array([[ 8,  9, 10]])

In [23]:
a2 = a1[2:4,0:4]
a2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
a2=a2.reshape(4,2)
a2



array([[ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

### VECTORIZATION

In [28]:
a1 = np.arange(0,12,2)
a1

array([ 0,  2,  4,  6,  8, 10])

In [29]:
a1*2

array([ 0,  4,  8, 12, 16, 20])

In [31]:
a1/2


array([0., 1., 2., 3., 4., 5.])